2022-10-21T15:26:38+0200 INFO --- logging initialized ---
2022-10-21T15:26:38+0200 DDEBUG timer: config: 47 ms
2022-10-21T15:26:38+0200 DEBUG Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync, system-upgrade
2022-10-21T15:26:38+0200 DDEBUG Cleaning up.
2022-10-21T15:27:06+0200 INFO --- logging initialized ---
2022-10-21T15:27:06+0200 DDEBUG timer: config: 1 ms
2022-10-21T15:27:06+0200 DEBUG Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync, system-upgrade
2022-10-21T15:27:06+0200 DEBUG DNF version: 4.13.0
2022-10-21T15:27:06+0200 DDEBUG Command: dnf --installroot=/home/Pojzo/Programming/c++/graphics/GA_pathfinding/temp install SFML 
2022-10-21T15:27:06+0200 DDEBUG Installroot: /home/Pojzo/Programming/c++/graphics/GA_pathfinding/temp
2022-10-21T15:27:06+0200 DDEBUG Releasever: None
2022-10-21T15:27:06+0200 DEBUG cachedir: /home/Pojzo/Programming/c++/graphics/GA_pathfinding/temp/var/cache/dnf
2022-10-21T15:27:06+0200 DDEBUG Base command: install
2022-10-21T15:27:06+0200 DDEBUG Extra commands: ['--installroot=/home/Pojzo/Programming/c++/graphics/GA_pathfinding/temp', 'install', 'SFML']
2022-10-21T15:27:06+0200 DEBUG User-Agent: constructed: 'libdnf (Fedora Linux 35; workstation; Linux.x86_64)'
2022-10-21T15:27:06+0200 DEBUG repo: downloading from remote: fedora
2022-10-21T15:27:06+0200 DEBUG countme: no event for fedora: budget to spend: 2
2022-10-21T15:27:06+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.159.254.57) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:06+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.159.254.57) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:06+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.159.254.57) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:06+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.159.254.57) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 85.236.55.6) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 85.236.55.6) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 85.236.55.6) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 85.236.55.6) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 DEBUG error: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134) (https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64).
2022-10-21T15:27:07+0200 WARNING Errors during downloading metadata for repository 'fedora':
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.159.254.57)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 85.236.55.6)
2022-10-21T15:27:07+0200 DDEBUG Cleaning up.
2022-10-21T15:27:07+0200 SUBDEBUG 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dnf/repo.py", line 573, in load
    ret = self._repo.load()
  File "/usr/lib64/python3.10/site-packages/libdnf/repo.py", line 331, in load
    return _repo.Repo_load(self)
libdnf._error.Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 122, in cli_run
    cli.run()
  File "/usr/lib/python3.10/site-packages/dnf/cli/cli.py", line 1040, in run
    self._process_demands()
  File "/usr/lib/python3.10/site-packages/dnf/cli/cli.py", line 741, in _process_demands
    self.base.fill_sack(
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 401, in fill_sack
    self._add_repo_to_sack(r)
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 141, in _add_repo_to_sack
    repo.load()
  File "/usr/lib/python3.10/site-packages/dnf/repo.py", line 580, in load
    raise dnf.exceptions.RepoError(str(e))
dnf.exceptions.RepoError: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134)
2022-10-21T15:27:07+0200 CRITICAL Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: 18.133.140.134)
